plugin:
 prefix: '&f[&b&lPrison&3&lNet&f]'

database:
 mysql:
  use: false
  host: ''
  password: ''
  username: ''
 
events:
 blocklist:
  use:
  list:
  - 'event_portal'
 mining:
  sound: 'CLICK'
  particles:
   particle: ''
   amount: 15
  expgain: 5
  
